In [1]:
from tdc.utils import retrieve_label_name_list
label_list = retrieve_label_name_list('TAP')
label_list

['CDR_Length', 'PSH', 'PPC', 'PNC', 'SFvCSP']

In [2]:
from tdc.single_pred import Develop
data_tap = Develop(name = 'TAP', label_name = label_list[0])
data_chen = Develop(name = 'SAbDab_Chen')
#split = data.get_split()


Found local copy...
Loading...
Done!
Found local copy...
Loading...
Done!


In [4]:
split = data_chen.get_split()

In [5]:
split['train']

Antibody_ID                                           Antibody  Y
0           12e8  ['EVQLQQSGAEVVRSGASVKLSCTASGFNIKDYYIHWVKQRPEKG...  0
1           15c8  ['EVQLQQSGAELVKPGASVKLSCTASGFNIKDTYMHWVKQKPEQG...  0
2           1a0q  ['EVQLQESDAELVKPGASVKISCKASGYTFTDHVIHWVKQKPEQG...  1
3           1a14  ['QVQLQQSGAELVKPGASVRMSCKASGYTFTNYNMYWVKQSPGQG...  0
4           1a2y  ['QVQLQESGPGLVAPSQSLSITCTVSGFSLTGYGVNWVRQPPGKG...  0
...          ...                                                ... ..
1681        6rcs  ['QVQLVQSGAEVKKPGASVRVSCKASGYTFTSYGISWVRQAPGQG...  0
1682        6s5a  ['EVKLLESGGGLVQPGGSLKLSCAASGFDFSRYWMNWVRQAPGKG...  0
1683        6u1t  ['EVQLVESGGGLVKPGGSLKLSCAASGFTFSSYDMSWVRQTPEKR...  0
1684        7fab  ['AVQLEQSGPGLVRPSQTLSLTCTVSGTSFDDYYWTWVRQPPGRG...  0
1685        8fab  ['AVKLVQAGGGVVQPGRSLRLSCIASGFTFSNYGMHWVRQAPGKG...  0

[1686 rows x 3 columns]

In [53]:
split['train'].to_csv("chen_train_data.csv", index=False, sep=";")

In [54]:
split['test'].to_csv("chen_test_data.csv", index=False, sep=";")
split['valid'].to_csv("chen_valid_data.csv", index=False, sep=";")

In [6]:
from pydpi import test
test.main()

Test successfully!


In [7]:
from pydpi.pypro import AAComposition

In [8]:
comp = AAComposition.CalculateAAComposition("PSSGHVCE")

In [9]:
comp

{'A': 0.0,
 'R': 0.0,
 'N': 0.0,
 'D': 0.0,
 'C': 12.5,
 'E': 12.5,
 'Q': 0.0,
 'G': 12.5,
 'H': 12.5,
 'I': 0.0,
 'L': 0.0,
 'K': 0.0,
 'M': 0.0,
 'F': 0.0,
 'P': 12.5,
 'S': 25.0,
 'T': 0.0,
 'W': 0.0,
 'Y': 0.0,
 'V': 12.5}

In [1]:
from pydpi.pypro import PyPro
protein = PyPro()
protein.ReadProteinSequence("PSSGHVCE")
desc = protein.GetALL()

ZeroDivisionError: division by zero

# PyBioMed

In [6]:
from PyBioMed import Pyprotein
protein="ADGCGVGEGTGQGPMCNCMCMKWVYADEDAADLESDSFADEDASLESDSFPWSNQRVFCSFADEDAS"
protein_class = Pyprotein.PyProtein(protein)
print(len(protein_class.GetDPComp()))

400


In [3]:
desc = protein_class.GetALL()

In [4]:
len(desc)

9880

In [5]:
desc

{'A': 11.94,
 'R': 1.493,
 'N': 2.985,
 'D': 14.925,
 'C': 7.463,
 'E': 8.955,
 'Q': 2.985,
 'G': 8.955,
 'H': 0.0,
 'I': 0.0,
 'L': 2.985,
 'K': 1.493,
 'M': 4.478,
 'F': 5.97,
 'P': 2.985,
 'S': 11.94,
 'T': 1.493,
 'W': 2.985,
 'Y': 1.493,
 'V': 4.478,
 'AA': 1.52,
 'AR': 0.0,
 'AN': 0.0,
 'AD': 7.58,
 'AC': 0.0,
 'AE': 0.0,
 'AQ': 0.0,
 'AG': 0.0,
 'AH': 0.0,
 'AI': 0.0,
 'AL': 0.0,
 'AK': 0.0,
 'AM': 0.0,
 'AF': 0.0,
 'AP': 0.0,
 'AS': 3.03,
 'AT': 0.0,
 'AW': 0.0,
 'AY': 0.0,
 'AV': 0.0,
 'RA': 0.0,
 'RR': 0.0,
 'RN': 0.0,
 'RD': 0.0,
 'RC': 0.0,
 'RE': 0.0,
 'RQ': 0.0,
 'RG': 0.0,
 'RH': 0.0,
 'RI': 0.0,
 'RL': 0.0,
 'RK': 0.0,
 'RM': 0.0,
 'RF': 0.0,
 'RP': 0.0,
 'RS': 0.0,
 'RT': 0.0,
 'RW': 0.0,
 'RY': 0.0,
 'RV': 1.52,
 'NA': 0.0,
 'NR': 0.0,
 'NN': 0.0,
 'ND': 0.0,
 'NC': 1.52,
 'NE': 0.0,
 'NQ': 1.52,
 'NG': 0.0,
 'NH': 0.0,
 'NI': 0.0,
 'NL': 0.0,
 'NK': 0.0,
 'NM': 0.0,
 'NF': 0.0,
 'NP': 0.0,
 'NS': 0.0,
 'NT': 0.0,
 'NW': 0.0,
 'NY': 0.0,
 'NV': 0.0,
 'DA': 4.55,
 'DR'

In [8]:
tripept = protein_class.GetTPComp()

In [9]:
len(tripept)

8000

In [23]:
tripept_list = list(tripept.values())

In [14]:
descriptors = list(desc.values())
len(descriptors)

9880

In [24]:
# 419 last dipeptide
descriptors = descriptors[:420] + tripept_list + descriptors[8420:]

In [26]:
len(descriptors)

9880

In [1]:
import numpy as np

In [8]:
def calculate_all_descriptors(sequence):
    protein = Pyprotein.PyProtein(sequence)
    desc = list(protein.GetALL().values())
    tripept = list(protein.GetTPComp().values())
    all_desc = desc[:420] + tripept + desc[8420:]
    return all_desc

In [15]:
def remove_excess(seq):
    seq = seq.replace("[", "").replace("]", "")
    seq = seq.replace("'", "")
    return seq.replace(",", "")

In [10]:
def descriptors_for_ab(seqs):
    heavy, light = seqs.split()
    heavy = remove_excess(heavy)
    light = remove_excess(light)
    desc_heavy = calculate_all_descriptors(heavy)
    desc_light = calculate_all_descriptors(light)
    all_desc = desc_heavy + desc_light
    return np.asarray(all_desc)

In [30]:
d = calculate_all_descriptors("KWVYADEDAADLESDSFADEDAS")
d

[21.739,
 0.0,
 0.0,
 26.087,
 0.0,
 13.043,
 0.0,
 0.0,
 0.0,
 0.0,
 4.348,
 4.348,
 0.0,
 4.348,
 0.0,
 13.043,
 0.0,
 4.348,
 4.348,
 4.348,
 4.55,
 0.0,
 0.0,
 13.64,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 4.55,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 9.09,
 0.0,
 0.0,
 0.0,
 0.0,
 9.09,
 0.0,
 0.0,
 0.0,
 0.0,
 4.55,
 0.0,
 0.0,
 0.0,
 0.0,
 4.55,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 9.09,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 4.55,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,


In [38]:
split['train']

Antibody_ID                                           Antibody  Y
0           12e8  ['EVQLQQSGAEVVRSGASVKLSCTASGFNIKDYYIHWVKQRPEKG...  0
1           15c8  ['EVQLQQSGAELVKPGASVKLSCTASGFNIKDTYMHWVKQKPEQG...  0
2           1a0q  ['EVQLQESDAELVKPGASVKISCKASGYTFTDHVIHWVKQKPEQG...  1
3           1a14  ['QVQLQQSGAELVKPGASVRMSCKASGYTFTNYNMYWVKQSPGQG...  0
4           1a2y  ['QVQLQESGPGLVAPSQSLSITCTVSGFSLTGYGVNWVRQPPGKG...  0
...          ...                                                ... ..
1681        6rcs  ['QVQLVQSGAEVKKPGASVRVSCKASGYTFTSYGISWVRQAPGQG...  0
1682        6s5a  ['EVKLLESGGGLVQPGGSLKLSCAASGFDFSRYWMNWVRQAPGKG...  0
1683        6u1t  ['EVQLVESGGGLVKPGGSLKLSCAASGFTFSSYDMSWVRQTPEKR...  0
1684        7fab  ['AVQLEQSGPGLVRPSQTLSLTCTVSGTSFDDYYWTWVRQPPGRG...  0
1685        8fab  ['AVKLVQAGGGVVQPGRSLRLSCIASGFTFSNYGMHWVRQAPGKG...  0

[1686 rows x 3 columns]

In [12]:
X = split["train"]["Antibody"].apply(descriptors_for_ab)
X.head()

0    [7.5, 3.333, 2.5, 5.833, 1.667, 5.833, 5.833, ...
1    [9.244, 0.0, 3.361, 5.882, 1.681, 4.202, 6.723...
2    [5.882, 1.681, 3.361, 5.042, 1.681, 5.882, 5.0...
3    [6.667, 2.5, 4.167, 5.0, 1.667, 2.5, 7.5, 11.6...
4    [3.448, 5.172, 4.31, 6.034, 1.724, 2.586, 6.03...
Name: Antibody, dtype: object

In [2]:
import pandas as pd

In [16]:
X_train_df = pd.DataFrame(X.to_list())

X_train_df.columns = X_train_df.columns.astype(str)
X_train_df.to_feather("X_train_data.ftr")

In [18]:
del(X)

In [19]:
X_test = split["test"]["Antibody"].apply(descriptors_for_ab)
X_test.head()

0    [5.785, 6.612, 1.653, 3.306, 1.653, 4.132, 2.4...
1    [4.202, 2.521, 5.882, 3.361, 1.681, 1.681, 7.5...
2    [3.448, 3.448, 3.448, 1.724, 1.724, 2.586, 5.1...
3    [5.042, 2.521, 6.723, 4.202, 1.681, 4.202, 5.0...
4    [1.709, 3.419, 2.564, 5.983, 1.709, 3.419, 5.9...
Name: Antibody, dtype: object

In [20]:
X_test_df = pd.DataFrame(X_test.to_list())

X_test_df.columns = X_test_df.columns.astype(str)
X_test_df.to_feather("X_test_data.ftr")

In [23]:
y_train = split['train']["Y"]
y_test = split['test']["Y"]

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
rf = RandomForestClassifier(n_estimators=100,
                           criterion="gini",
                           bootstrap=True,
                           random_state=42)
rf.fit(X_train_df, y_train)
y_pred = rf.predict(X_test_df)

In [3]:
from sklearn.metrics import confusion_matrix, classification_report

In [26]:
confusion_matrix(y_test, y_pred)

array([[350,  16],
       [ 66,  50]], dtype=int64)

In [27]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.96      0.90       366
           1       0.76      0.43      0.55       116

    accuracy                           0.83       482
   macro avg       0.80      0.69      0.72       482
weighted avg       0.82      0.83      0.81       482



In [28]:
def random_forest_test(n, criterion):
    rf_n = RandomForestClassifier(n_estimators=n,
                           criterion=criterion,
                           bootstrap=True,
                           random_state=42)
    rf_n.fit(X_train_df, y_train)
    y_pred = rf_n.predict(X_test_df)
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))

In [30]:
for num in [150, 200, 300]:
    for crit in ["gini", "entropy"]:
        print(f"n_estimators: {num}; criterion: {crit}")
        random_forest_test(num, crit)
        print("============")

n_estimators: 150; criterion: gini
[[350  16]
 [ 65  51]]
              precision    recall  f1-score   support

           0       0.84      0.96      0.90       366
           1       0.76      0.44      0.56       116

    accuracy                           0.83       482
   macro avg       0.80      0.70      0.73       482
weighted avg       0.82      0.83      0.81       482

n_estimators: 150; criterion: entropy
[[350  16]
 [ 66  50]]
              precision    recall  f1-score   support

           0       0.84      0.96      0.90       366
           1       0.76      0.43      0.55       116

    accuracy                           0.83       482
   macro avg       0.80      0.69      0.72       482
weighted avg       0.82      0.83      0.81       482

n_estimators: 200; criterion: gini
[[350  16]
 [ 67  49]]
              precision    recall  f1-score   support

           0       0.84      0.96      0.89       366
           1       0.75      0.42      0.54       116

    a

In [39]:
from sklearn.svm import LinearSVC, SVC

In [37]:
def linear_SVM_test(penalty, loss):
    lsvc = LinearSVC(penalty=penalty,
                     loss=loss,
                     random_state=42,
                     class_weight='balanced')
    lsvc.fit(X_train_df, y_train)
    y_pred = lsvc.predict(X_test_df)
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))

In [38]:
for pen in ['l2']:   # The combination of penalty='l1' and loss='squared_hinge' are not supported when dual=True
    for loss in ["hinge", "squared_hinge"]:
        print(f"penalty: {pen}; loss: {loss}")
        linear_SVM_test(pen, loss)
        print("============")

penalty: l2; loss: hinge
[[365   1]
 [103  13]]
              precision    recall  f1-score   support

           0       0.78      1.00      0.88       366
           1       0.93      0.11      0.20       116

    accuracy                           0.78       482
   macro avg       0.85      0.55      0.54       482
weighted avg       0.82      0.78      0.71       482

penalty: l2; loss: squared_hinge
[[365   1]
 [103  13]]
              precision    recall  f1-score   support

           0       0.78      1.00      0.88       366
           1       0.93      0.11      0.20       116

    accuracy                           0.78       482
   macro avg       0.85      0.55      0.54       482
weighted avg       0.82      0.78      0.71       482



In [42]:
def C_SVM_test(c, kernel, degree=3):
    svc = SVC(C=c,
               kernel=kernel,
               random_state=42,
               degree=degree)
    svc.fit(X_train_df, y_train)
    y_pred = svc.predict(X_test_df)
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))

In [44]:
for c in [0.5, 1, 1.5]:   
    for kernel in ["linear", "poly", "rbf", "sigmoid"]:
        if kernel == 'poly':
            for deg in [2, 3, 4]:
                print(f"C: {c}; kernel: {kernel}; degree: {deg}")
                C_SVM_test(c, kernel, deg)
                print("============")
        else:
            print(f"C: {c}; kernel: {kernel}")
            C_SVM_test(c, kernel)
            print("============")

C: 0.5; kernel: linear
[[330  36]
 [ 44  72]]
              precision    recall  f1-score   support

           0       0.88      0.90      0.89       366
           1       0.67      0.62      0.64       116

    accuracy                           0.83       482
   macro avg       0.77      0.76      0.77       482
weighted avg       0.83      0.83      0.83       482

C: 0.5; kernel: poly; degree: 2
[[366   0]
 [116   0]]
              precision    recall  f1-score   support

           0       0.76      1.00      0.86       366
           1       0.00      0.00      0.00       116

    accuracy                           0.76       482
   macro avg       0.38      0.50      0.43       482
weighted avg       0.58      0.76      0.66       482

C: 0.5; kernel: poly; degree: 3
[[366   0]
 [116   0]]
              precision    recall  f1-score   support

           0       0.76      1.00      0.86       366
           1       0.00      0.00      0.00       116

    accuracy              

In [47]:
from sklearn.linear_model import LogisticRegression

In [49]:
def logistic_regression_test(penalty, c, solver):
    lr = LogisticRegression(C=c,
               penalty=penalty,
               class_weight='balanced',
               random_state=42,
               solver=solver)
    lr.fit(X_train_df, y_train)
    y_pred = lr.predict(X_test_df)
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))

In [51]:
for c in [0.5, 1, 1.5]:   
    for penalty in ["l1", "l2", "elasticnet", "none"]:
        for solver in ["newton-cg", "lbfgs", "liblinear", "sag", "saga"]:
        
            print(f"C: {c}; penalty: {penalty}; solver: {solver}")
            try:
                logistic_regression_test(penalty, c, solver)
            except ValueError as e:
                print(e)
            print("============")

C: 0.5; penalty: l1; solver: newton-cg
Solver newton-cg supports only 'l2' or 'none' penalties, got l1 penalty.
C: 0.5; penalty: l1; solver: lbfgs
Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.
C: 0.5; penalty: l1; solver: liblinear
[[323  43]
 [ 39  77]]
              precision    recall  f1-score   support

           0       0.89      0.88      0.89       366
           1       0.64      0.66      0.65       116

    accuracy                           0.83       482
   macro avg       0.77      0.77      0.77       482
weighted avg       0.83      0.83      0.83       482

C: 0.5; penalty: l1; solver: sag
Solver sag supports only 'l2' or 'none' penalties, got l1 penalty.
C: 0.5; penalty: l1; solver: saga
[[291  75]
 [ 27  89]]
              precision    recall  f1-score   support

           0       0.92      0.80      0.85       366
           1       0.54      0.77      0.64       116

    accuracy                           0.79       482
   macro avg       0

In [52]:
split['train']["Y"].mean()

0.19098457888493475

In [59]:
X_valid = split["valid"]["Antibody"].apply(descriptors_for_ab)
X_valid.head()

0    [8.036, 1.786, 0.893, 4.464, 1.786, 4.464, 6.2...
1    [3.906, 3.906, 0.781, 2.344, 1.562, 3.906, 4.6...
2    [3.448, 1.724, 5.172, 2.586, 1.724, 4.31, 5.17...
3    [6.667, 6.667, 4.167, 5.0, 1.667, 3.333, 3.333...
4    [4.545, 6.061, 2.273, 5.303, 1.515, 1.515, 3.0...
Name: Antibody, dtype: object

In [60]:
df_valid = pd.DataFrame(X_valid.to_list())

df_valid.columns = df_valid.columns.astype(str)
df_valid.to_feather("X_valid_data.ftr")

## Embeddings
Load data from files

In [29]:
import pandas as pd
import numpy as np
import os

In [30]:
X_train = pd.read_feather("data/X_train_data.ftr")
X_test = pd.read_feather("data/X_test_data.ftr")
X_valid = pd.read_feather("data/X_valid_data.ftr")

In [31]:
X_train.head()

Ab_ID      0      1      2      3      4      5      6       7      8  ...  \
0  12e8  7.500  3.333  2.500  5.833  1.667  5.833  5.833   9.167  1.667  ...   
1  15c8  9.244  0.000  3.361  5.882  1.681  4.202  6.723   8.403  2.521  ...   
2  1a0q  5.882  1.681  3.361  5.042  1.681  5.882  5.042   9.244  1.681  ...   
3  1a14  6.667  2.500  4.167  5.000  1.667  2.500  7.500  11.667  0.000  ...   
4  1a2y  3.448  5.172  4.310  6.034  1.724  2.586  6.034  10.345  0.862  ...   

   19750  19751  19752  19753  19754  19755  19756  19757  19758  19759  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 19761 columns]

In [4]:
data_train = pd.read_csv("data/chen_train_data.csv", sep=";")
data_valid = pd.read_csv("data/chen_valid_data.csv", sep=";")
data_test = pd.read_csv("data/chen_test_data.csv", sep=";")

In [1]:
from embeddings_reproduction import embedding_tools

In [5]:
seqs = ["ACVMSTRDA", "FTSDACPLMTSST"]

In [9]:
embeds = embedding_tools.get_embeddings_new('../embed_models/original_3_1.pkl', seqs, k=5, overlap=False)

In [10]:
pd.DataFrame.from_records(embeds)

0         1         2         3         4         5         6   \
0 -0.014781 -0.001247  0.268215 -0.027002  0.237463 -0.252756 -0.163913   
1 -0.103935 -0.168398 -0.267852  0.095176 -0.052804 -0.036648 -0.306973   

         7         8         9   ...       54        55        56        57  \
0 -0.184446  0.089368 -0.120450  ... -0.21672  0.169656 -0.027164 -0.114215   
1  0.048839  0.099976 -0.174751  ...  0.00361  0.022153 -0.147477  0.180707   

         58        59        60        61        62        63  
0  0.051775 -0.236802  0.023171 -0.096376  0.160871  0.031065  
1 -0.061898  0.054925 -0.154312 -0.003939  0.071967  0.054054  

[2 rows x 64 columns]

In [19]:
def embed_sequences(data, model_path, out_path, k=5, overlap=False):
    embeds_data = []
    split = data["Antibody"].str.split()
    heavy = [remove_excess(seqs[0]) for seqs in split]
    light = [remove_excess(seqs[1]) for seqs in split]
    for seqlist in [heavy, light]:
        embeds = embedding_tools.get_embeddings(model_path, seqlist, k, overlap)
        embeds_data.append(pd.DataFrame.from_records(embeds))
    ncols = len(embeds_data[0].columns)
    embeds_pd = pd.concat(embeds_data, axis=1)
    embeds_pd.columns = [str(i) for i in range(ncols)] + [str(i) + "_2" for i in range(ncols)]
    embeds_pd.insert(0, "Ab_ID", data["Antibody_ID"])
    #embeds_pd.to_csv(out_path, index=False)
    embeds_pd.to_feather(out_path)
    return embeds_pd

In [20]:
models = [mod_file for mod_file in os.listdir("../embed_models") if mod_file.endswith(".pkl")]
for model in models:
    mod_name = model.split(".")[0]
    outfile = f"data/embeddings/embeddings_train_{mod_name}.ftr"
    k = int(mod_name.split("_")[1])
    w = int(mod_name.split("_")[2])
    df = embed_sequences(data_train, f"../embed_models/{model}", outfile, k=k)
    #print(outfile)

In [21]:
for model in models:
    mod_name = model.split(".")[0]
    outfile = f"data/embeddings/embeddings_test_{mod_name}.ftr"
    k = int(mod_name.split("_")[1])
    w = int(mod_name.split("_")[2])
    df = embed_sequences(data_test, f"../embed_models/{model}", outfile, k=k)
    #print(outfile)

In [22]:
for model in models:
    mod_name = model.split(".")[0]
    outfile = f"data/embeddings/embeddings_valid_{mod_name}.ftr"
    k = int(mod_name.split("_")[1])
    w = int(mod_name.split("_")[2])
    df = embed_sequences(data_valid, f"../embed_models/{model}", outfile, k=k)

In [23]:
embed_train = pd.read_feather("data/embeddings/embeddings_train_original_3_1.ftr")

In [24]:
embed_train.head()

Ab_ID         0         1         2         3         4         5         6  \
0  12e8 -0.119551 -0.081851 -0.074167  0.152037  0.129428  0.085095 -0.030417   
1  15c8  0.021530 -0.304652 -0.132556  0.061507  0.150677  0.098915  0.041480   
2  1a0q  0.039578 -0.165334 -0.022410 -0.080268  0.047611  0.048944  0.080545   
3  1a14  0.120464 -0.081033 -0.107538  0.061656  0.173956  0.004049  0.124448   
4  1a2y  0.014664 -0.076477 -0.047139  0.041975  0.182140  0.069364  0.023516   

          7         8  ...      54_2      55_2      56_2      57_2      58_2  \
0 -0.110267  0.075634  ...  0.200469 -0.046869 -0.001064  0.103459  0.151518   
1 -0.203386  0.016552  ... -0.045949 -0.127985  0.078211  0.220624 -0.137954   
2 -0.236821  0.112831  ...  0.057385 -0.050525  0.202889  0.261739  0.002610   
3 -0.198621  0.236676  ... -0.143312 -0.143539  0.047924  0.310107  0.048446   
4 -0.239836 -0.025285  ... -0.028963 -0.108840  0.098158  0.180053  0.178013   

       59_2      60_2      61_2      62_2      63_2  
0 -0.026898 -0.233277  0.051276 -0.014353 -0.304066  
1 -0.084574 -0.039934  0.067366 -0.051279 -0.253232  
2 -0.052941 -0.150026  0.250437  0.170185 -0.221552  
3 -0.046024 -0.050520 -0.020289  0.010511 -0.186632  
4  0.103138 -0.067108  0.154135  0.236273 -0.290542  

[5 rows x 129 columns]

In [25]:
X_train.head()

0      1      2      3      4      5      6       7      8      9  ...  \
0  7.500  3.333  2.500  5.833  1.667  5.833  5.833   9.167  1.667  4.167  ...   
1  9.244  0.000  3.361  5.882  1.681  4.202  6.723   8.403  2.521  3.361  ...   
2  5.882  1.681  3.361  5.042  1.681  5.882  5.042   9.244  1.681  4.202  ...   
3  6.667  2.500  4.167  5.000  1.667  2.500  7.500  11.667  0.000  1.667  ...   
4  3.448  5.172  4.310  6.034  1.724  2.586  6.034  10.345  0.862  2.586  ...   

   19750  19751  19752  19753  19754  19755  19756  19757  19758  19759  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 19760 columns]

In [27]:
X_train.insert(0, "Ab_ID", data_train["Antibody_ID"])
X_test.insert(0, "Ab_ID", data_test["Antibody_ID"])
X_valid.insert(0, "Ab_ID", data_valid["Antibody_ID"])
X_train.head()

Ab_ID      0      1      2      3      4      5      6       7      8  ...  \
0  12e8  7.500  3.333  2.500  5.833  1.667  5.833  5.833   9.167  1.667  ...   
1  15c8  9.244  0.000  3.361  5.882  1.681  4.202  6.723   8.403  2.521  ...   
2  1a0q  5.882  1.681  3.361  5.042  1.681  5.882  5.042   9.244  1.681  ...   
3  1a14  6.667  2.500  4.167  5.000  1.667  2.500  7.500  11.667  0.000  ...   
4  1a2y  3.448  5.172  4.310  6.034  1.724  2.586  6.034  10.345  0.862  ...   

   19750  19751  19752  19753  19754  19755  19756  19757  19758  19759  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 19761 columns]

In [28]:
X_train.to_feather("data/X_train_data.ftr")
X_test.to_feather("data/X_test_data.ftr")
X_valid.to_feather("data/X_valid_data.ftr")

In [1]:
from abnumber import Chain